import {chromium} from 'playwright-core';
import path from 'node:path';import fs from 'node:fs';
const root=process.cwd(),url='file:///'+path.join(root,'index.html').replaceAll('\\','/');
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
const page=await browser.newPage({viewport:{width:1366,height:768},reducedMotion:'reduce'});
const issues=[];page.on('pageerror',e=>issues.push(e.message));
await page.goto(url+'#6');await page.waitForTimeout(80);
const hiddenBefore=await page.locator('.slide.is-active .conclusion-symbol').evaluate(el=>getComputedStyle(el).visibility);
await page.locator('.slide.is-active [data-reveal]').click();const shownAfter=await page.locator('.slide.is-active .conclusion-symbol').evaluate(el=>getComputedStyle(el).visibility);
await page.goto(url+'#12');await page.locator('.fallacy-list summary').nth(1).click();await page.screenshot({path:path.join(root,'screenshots','fallacy-expanded.png')});
await page.goto(url+'#13');await page.locator('#truthTableButton').click();await page.screenshot({path:path.join(root,'screenshots','truth-table-complete.png')});
await page.goto(url+'#15');await page.locator('#explainButton').click();for(let i=0;i<5;i++)await page.locator('#nextExplanation').click();await page.screenshot({path:path.join(root,'screenshots','proof-caption-final-step.png')});
const proofCaption=await page.locator('#narrationText').textContent();const proofVisible=await page.locator('.proof-step:visible').count();
await page.locator('#stopNarration').click();await page.locator('#explainButton').click();const replayStep=await page.locator('#narrationStepCount').textContent();
await page.goto(url+'#17');for(const [name,value] of [['q1','a'],['q2','b'],['q3','a']])await page.locator(`input[name="${name}"][value="${value}"]`).check();await page.locator('#challengeForm button[type="submit"]').click();await page.screenshot({path:path.join(root,'screenshots','quiz-feedback.png')});
await page.goto(url+'#5');await page.locator('[data-go="modus-ponens"]').click();await page.waitForTimeout(40);const linkTarget=await page.locator('.slide.is-active').getAttribute('data-id');
await page.keyboard.press('ArrowRight');await page.waitForTimeout(40);const keyboardTarget=await page.locator('.slide.is-active').getAttribute('data-id');
await page.goto(url+'#11');await page.locator('#builderNext').click();await page.locator('#builderNext').click();await page.screenshot({path:path.join(root,'screenshots','proof-builder-complete.png')});
await page.emulateMedia({media:'print'});const printFit=await page.locator('.slide').evaluateAll(slides=>slides.map((s,i)=>{const sr=s.getBoundingClientRect(),cr=s.querySelector('.content')?.getBoundingClientRect();return {n:i+1,contentBottom:cr?Math.round(cr.bottom-sr.bottom):null,contentRight:cr?Math.round(cr.right-sr.right):null}}));
await page.pdf({path:path.join(root,'handout-check.pdf'),printBackground:true,landscape:true,format:'A4',preferCSSPageSize:true});
const phone=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,reducedMotion:'reduce'});await phone.goto(url+'#13');await phone.locator('.slide.is-active .content').evaluate(el=>el.scrollTop=el.scrollHeight);const tableButtonVisible=await phone.locator('#truthTableButton').isVisible();await phone.locator('#truthTableButton').click();const tableVisible=await phone.locator('#truthTable').isVisible();
await phone.goto(url+'#16');const phoneBox=await phone.locator('#doodle').boundingBox();await phone.touchscreen.tap(phoneBox.x+30,phoneBox.y+30);const undoAvailable=await phone.locator('#undoDoodle').isEnabled();
const noVoice=await browser.newPage({viewport:{width:1366,height:768}});await noVoice.addInitScript(()=>{Object.defineProperty(window,'speechSynthesis',{value:undefined,configurable:true});});await noVoice.goto(url+'#4');await noVoice.locator('#explainButton').click();const noVoiceCaption=await noVoice.locator('#narrationText').textContent();
console.log(JSON.stringify({hiddenBefore,shownAfter,proofCaption,proofVisible,replayStep,linkTarget,keyboardTarget,printFit,tableButtonVisible,tableVisible,undoAvailable,noVoiceCaption,issues},null,2));
await browser.close();
