import { chromium } from 'playwright-core';
import path from 'node:path';
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--disable-background-networking']});
const root=process.cwd(),url='file:///'+path.join(root,'index.html').replaceAll('\\','/'),out=path.join(root,'responsive-screenshots');
const page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,reducedMotion:'reduce'});
await page.goto(url+'#15');await page.locator('#explainButton').click();for(let i=0;i<3;i++)await page.locator('#nextExplanation').click();
await page.screenshot({path:path.join(out,'portrait-390x844-proof.png')});
await page.setViewportSize({width:844,height:390});await page.waitForTimeout(250);
await page.screenshot({path:path.join(out,'landscape-844x390-proof.png')});
await page.goto(url+'#17');for(const [n,v] of [['q1','a'],['q2','b'],['q3','a']])await page.locator(`input[name="${n}"][value="${v}"]`).check();await page.locator('#challengeForm button[type="submit"]').click();
await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,'portrait-390x844-quiz.png')});
await page.goto(url+'#13');await page.locator('#truthTableButton').click();await page.setViewportSize({width:844,height:390});await page.locator('#truthTable').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'landscape-844x390-truth.png')});
await page.goto(url+'#15');await page.setViewportSize({width:568,height:320});await page.screenshot({path:path.join(out,'landscape-568x320-proof.png')});
await browser.close();
